# Generated by Django 3.1.4 on 2020-12-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_bookinstance_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='language',
            field=models.CharField(blank=True, choices=[('p', 'Portuguese'), ('f', 'Farsi')], default='p', help_text='Book Language', max_length=1),
        ),
    ]
